#!/usr/bin/env bash

# Kill hyprpaper to save resources
pkill hyprpaper

# Directory containing video wallpapers
WALLPAPER_DIR="$HOME/Pictures/wallpaper-archive/Dynamic-Wallpapers/"

# Get current wallpaper if any is running
CURRENT_WALL=$(pgrep -af "mpv --wallpaper" | grep -o '[^ ]*$' | head -n 1 || echo "none")

# Kill any existing mpvpaper instances
pkill mpvpaper

# Get random video wallpaper different from current
WALLPAPER=$(find "$WALLPAPER_DIR" -type f -iname "*.mp4" ! -name "$(basename "$CURRENT_WALL")" | shuf -n 1)

# Apply the random live wallpaper
mpvpaper -s -o "no-audio loop" eDP-1 "$WALLPAPER"
