#!/usr/bin/env bash
# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/
pkill mpvpaper
if pgrep mpvpaper >/dev/null; then
    pkill mpvpaper
fi

WALLPAPER_DIR="$WALLPAPER_ARCHIVE_PATH/Static-Wallpapers"

if ! pgrep hyprpaper >/dev/null; then
    hyprpaper &
    sleep 1 # Give it a moment to initialize
fi

CURRENT_WALL=$(hyprctl hyprpaper listloaded)

WALLPAPER=$(find "$WALLPAPER_DIR" -type f ! -name "$(basename "$CURRENT_WALL")" | shuf -n 1)

hyprctl hyprpaper reload ,"$WALLPAPER"
