#!/usr/bin/env bash
{
    music_dir="$HOME/storage/downloads/Music"
    video_dir="$HOME/storage/downloads/Videos/To-Watch"

    (
        echo "Downloading 'To-Watch' into $video_dir"
        yt-dlp -P "$video_dir" -w -c --no-abort-on-error "https://youtube.com/playlist?list=PLBBcaljFGSiSTqrzKibZJqKwzHiEEn1gc&si=KE_sh_KEKHZphj32"
    ) &

    declare -A playlists=(
        ["Haven"]="https://youtube.com/playlist?list=PLBBcaljFGSiSz8czPRv3tX3C4nKo4On4j&si=YCIbnJX6xgvrvmlV"
        ["Eternal-Haven"]="https://youtube.com/playlist?list=PLBBcaljFGSiSZ5enBdlyxcqu0RZtpuuoq&si=xHGIPd-Uw-7DeBZE"
        ["Instrumental-Haven"]="https://youtube.com/playlist?list=PLBBcaljFGSiQb-vXx89JDd9QXoa_iQjGA&si=yIH54ZTJQtO4vzsF"
        ["Eternal-Instruemental-Haven"]="https://youtube.com/playlist?list=PLBBcaljFGSiSMYqaq-Vs-1hmnMyCvzW7D&si=8af86RAPfGnFQ5fE"
    )

    for folder in "${!playlists[@]}"; do
        dir="$music_dir/$folder"
        url="${playlists[$folder]}"
        (
            yt-dlp -P "$dir" -w -c --no-abort-on-error -x --audio-format best "$url"
        ) &
    done
    wait
    echo "All downloads completed."
}
