#!/usr/bin/env bash

pacman_tools=(
    git
    curl
    fzf
    tree
    neovim
    zsh
    shellcheck
    rust-analyzer
    tmux
    htop
    ripgrep
    rofi-wayland
    yazi
    gimp
    hyprpaper
    hypridle
    hyprlock
    hyprpicker
    uwsm
    thunar
    btop
    fastfetch
    grub-customizer
    nwg-look
    timeshift
    playerctl
    sound-theme-freedestop
)
aur_tools=(
    zen-browser-bin
    visual-studio-code-bin
    ttf-jetbrains-mono-nerd
    sddm-theme-greenleaf
    hyprcursor
    rose-pine-hyprcursor
    mpvpaper
    hyprpanel
)

echo "== Tools to be installed with pacman =="
for tool in "${pacman_tools[@]}"; do
    echo " - $tool"
done

echo -e "\n== Tools to be installed with yay (AUR) =="
for tool in "${aur_tools[@]}"; do
    echo " - $tool"
done

read -p $'\nDo you want to install them? (y/n): ' choice

if [[ "$choice" == "y" ]]; then
    echo -e "\n📦 Installing pacman tools..."
    for tool in "${pacman_tools[@]}"; do
        echo "Installing $tool..."
        sudo pacman -S --noconfirm --needed $tool
    done

    echo -e "\n🎯 Installing AUR tools with yay..."
    for tool in "${aur_tools[@]}"; do
        echo "Installing $tool..."
        yay -S --noconfirm --needed $tool
    done

    echo -e "\n✅ All tools installed!"
else
    echo "❌ Installation cancelled."
fi
