#!/usr/bin/env bash

PROCESS_NAME=".waybar-wrapped"

if pgrep -x "$PROCESS_NAME" >/dev/null; then
    pkill -x $PROCESS_NAME
    notify-send "Turning Waybar off"
else
    waybar &
    notify-send "Turning Waybar on"
fi
