[env]
TERM                  = "xterm-256color"
LANG = "en_US.UTF-8"
LC_ALL= "en_US.UTF-8"

# Window settings
[window]
padding.x = 2
padding.y = 2
dynamic_padding= true
decorations = "full"
opacity = 0.8
blur = true

# Scrolling
[scrolling]
history = 10000
multiplier = 3



[font]
normal                = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold                  = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic                = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic           = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size                  = 11.25
offset                = { x = 0, y = 0 }
glyph_offset          = { x = 0, y = 0 }
builtin_box_drawing   = true


# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
foreground = "#e0def4"
background = "#191724"
dim_foreground = "#908caa"
bright_foreground = "#e0def4"

[colors.cursor]
text = "#e0def4"
cursor = "#524f67"

[colors.vi_mode_cursor]
text = "#e0def4"
cursor = "#524f67"

[colors.search.matches]
foreground = "#908caa"
background = "#26233a"

[colors.search.focused_match]
foreground = "#191724"
background = "#ebbcba"

[colors.hints.start]
foreground = "#908caa"
background = "#1f1d2e"

[colors.hints.end]
foreground = "#6e6a86"
background = "#1f1d2e"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#e0def4"
background = "#1f1d2e"

[colors.selection]
text = "#e0def4"
background = "#403d52"

[colors.normal]
black = "#26233a"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

[colors.bright]
black = "#6e6a86"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"

[colors.dim]
black = "#6e6a86"
red = "#eb6f92"
green = "#31748f"
yellow = "#f6c177"
blue = "#9ccfd8"
magenta = "#c4a7e7"
cyan = "#ebbcba"
white = "#e0def4"



# # catpuccin-mocha, ported from .yml
# [colors.primary]
# background            = "#1E1E2E"
# foreground            = "#CDD6F4"
# dim_foreground        = "#CDD6F4"
# bright_foreground     = "#CDD6F4"
#
# [colors.cursor]
# text                  = "#1E1E2E"
# cursor                = "#F5E0DC"
#
# [colors.vi_mode_cursor]
# text                  = "#1E1E2E"
# cursor                = "#B4BEFE"
#
# [colors.search.matches]
# foreground            = "#1E1E2E"
# background            = "#A6ADC8"
#
# [colors.search.focused_match]
# foreground            = "#1E1E2E"
# background            = "#A6E3A1"
#
# [colors.hints.start]
# foreground            = "#1E1E2E"
# background            = "#F9E2AF"
#
# [colors.hints.end]
# foreground            = "#1E1E2E"
# background            = "#A6ADC8"
#
# [colors.line_indicator]
# #foreground            = "None"
# #background            = "None"
#
# [colors.footer_bar]
# foreground            = "#1E1E2E"
# background            = "#A6ADC8"
#
# [colors.selection]
# text                  = "#1E1E2E"
# background            = "#F5E0DC"
#
# [colors.normal]
# black                 = "#45475A"
# red                   = "#F38BA8"
# green                 = "#A6E3A1"
# yellow                = "#F9E2AF"
# blue                  = "#89B4FA"
# magenta               = "#F5C2E7"
# cyan                  = "#94E2D5"
# white                 = "#BAC2DE"
#
# [colors.bright]
# black                 = "#585B70"
# red                   = "#F38BA8"
# green                 = "#A6E3A1"
# yellow                = "#F9E2AF"
# blue                  = "#89B4FA"
# magenta               = "#F5C2E7"
# cyan                  = "#94E2D5"
# white                 = "#A6ADC8"
#
# [colors.dim]
# black                 = "#45475A"
# red                   = "#F38BA8"
# green                 = "#A6E3A1"
# yellow                = "#F9E2AF"
# blue                  = "#89B4FA"
# magenta               = "#F5C2E7"
# cyan                  = "#94E2D5"
# white                 = "#BAC2DE"
#
[colors]
indexed_colors = [
  { index = 16, color = "#FAB387" },
  { index = 17, color = "#F5E0DC" },
]
transparent_background_colors = false
draw_bold_text_with_bright_colors = true
