#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$(realpath "$1")
else
    selected=$(find ~ -mindepth 1 -maxdepth 4 -type d 2>/dev/null | fzf)
    selected=$(realpath "$selected")
fi

if [[ -z "$selected" ]]; then
    exit 1
fi

if [[ "$PWD" == "$selected" ]]; then
    exit 0
fi

if [[ -d "$selected" ]]; then
    cd "$selected" || {
        exit 1
    }
    echo "Successfully changed to directory: $selected"
else
    echo "No such directory found: $selected"
    exit 1
fi
