#!/usr/bin/env bash
# ANSI color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Ensure the script runs with root privileges
if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}Please run as root: sudo ${NC}"
    exit 1
fi

echo -e "${RED}Error:${NC} Dang you already gave me sudo permission !!!"
sleep 2
echo -e "${GREEN}I won't do that bad.${NC}"
sleep 2
# Define the list of packages
packages=(
    fastfetch
    git
    nodejs
    npm
    gcc
    python3
    neovim
    stow
    tmux
    unzip
    wget
    ripgrep
    ruby
    luarocks
    python-pip
    php
    cargo
    xclip
    lazygit
    tree-sitter
    shellcheck
)

# Install packages using pacman arch by the way ..
echo -e "${BLUE}Info:${NC} Installing packages..."

pacman -S --noconfirm "${packages[@]}"

cd "/root" || {
    echo -e "${RED}Error:${NC} Failed to navigate to /root directory."
    echo -e "${BLUE}Info:${NC} Aborting...\n"
    sleep 2
    exit 1
}

echo -e "${BLUE}Cloning:${NC} The tmux plugin manager that you gonna use ..." && sleep 2
git clone https://github.com/tmux-plugins/tpm "/root/.tmux/plugins/tpm"

# Clone dotfiles repository
cd "/root" || {
    echo -e "${RED}Error:${NC} Failed to navigate to root directory."
    echo -e "${BLUE}Info:${NC} Aborting...\n"
    sleep 2
    exit 1
}

echo -e "${BLUE}Cloning:${NC} Dotfiles form main branch..."
git clone --depth=1 -b main https://github.com/santoshxshrestha/dotfiles.git "/root/dotfiles/"

# Stow the dotfiles
cd "/root/dotfiles" || {
    echo -e "${RED}Error:${NC} Failed to navigate to /root directory."
    echo -e "${BLUE}Info:${NC} Aborting...\n"
    sleep 2
    exit 1
}
echo -e "Stowing dotfiles..."
stow nvim tmux fastfetch

cd "/root" || {
    echo -e "${RED}Error:${NC} Failed to navigate to /root directory."
    echo -e "${BLUE}Info:${NC} Aborting...\n"
    sleep 2
    exit 1
}

# This package (neovim on npm) is a Node.js client for Neovim’s RPC API.
#It allows Node.js applications (like Neovim plugins) to send commands and interact with Neovim.
npm install -g neovim

fastfetch
sleep 2
echo -e "${GREEN}Setup complete!${NC}"
echo -e "${GREEN}
Your Neovim configuration is ready. 
${NC}Launch Neovim in the terminal. 
On first launch, the package manager will automatically install all plugins. 
You may see installation progress messages. 
Once complete, restart Neovim for all features to be fully activated.
"
