# Starship Configuration - Black and White with Nerd Fonts
# Save this as ~/.config/starship.toml

# Add a blank line between shell prompts
add_newline = true

# Timeout for commands (in milliseconds)
command_timeout = 500

# Main prompt format - customize the order and modules you want
format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$java\
$cmd_duration\
$line_break\
$character"""

# Right side prompt format
right_format = """$all"""

# Directory module - shows current path
[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"
read_only = " "
style = "bold white"
read_only_style = "bold white"
format = "[$path]($style)[$read_only]($read_only_style) "

# Git branch
[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold white"
truncation_length = 20
truncation_symbol = "…"

# Git commit
[git_commit]
commit_hash_length = 7
format = "[$hash$tag]($style) "
style = "bold white"
only_detached = true
tag_symbol = " "
tag_disabled = false

# Git state (for operations like merge, rebase, etc.)
[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
style = "bold white"
cherry_pick = " PICKING"
bisect = " BISECTING"
am = " AM"
am_or_rebase = " AM/REBASE"
merge = " MERGING"
rebase = " REBASING"

# Git metrics - shows insertions/deletions
[git_metrics]
added_style = "bold white"
deleted_style = "bold white"
format = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
disabled = false

# Git status - shows working directory status
[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold white"
conflicted = " "
ahead = " ${count} "
behind = " ${count} "
diverged = " ${ahead_count} ${behind_count} "
untracked = " ${count} "
stashed = " "
modified = " ${count} "
staged = " ${count} "
renamed = " ${count} "
deleted = " ${count} "

# Command duration - shows execution time
[cmd_duration]
min_time = 500
format = "took [$duration]($style) "
style = "bold white"
show_milliseconds = true

# Character module - the prompt character
[character]
success_symbol = "[✦ ❯](bold white)"
error_symbol = "[❯](bold white)"
vicmd_symbol = "[❮](bold white)"

# Language-specific modules
[python]
symbol = " "
format = 'via [$symbol$pyenv_prefix($version)(\($virtualenv\))]($style) '
style = "bold white"
pyenv_version_name = true
python_binary = ["python", "python3", "python2"]

[nodejs]
symbol = " "
format = "via [$symbol($version)]($style) "
style = "bold white"
detect_files = ["package.json", ".nvmrc"]

[rust]
symbol = " "
format = "via [$symbol($version)]($style) "
style = "bold white"

[golang]
symbol = " "
format = "via [$symbol($version)]($style) "
style = "bold white"

[java]
symbol = " "
format = "via [$symbol($version)]($style) "
style = "bold white"

# Disabled modules (to exclude hostname, time, etc.)
[hostname]
disabled = true

[time]
disabled = true

[username]
disabled = true

[battery]
disabled = true

[memory_usage]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[docker_context]
disabled = true

[kubernetes]
disabled = true
