keys:
  - &users:
    - &santosh CF2DBDF1A619C8EC2682B3A2E7D593EEA66CA06D
  - &hosts:
    - &helios age108jsv2nyy6k3aqrz9crx08sc39lf6vvpa8tmmldrrff8t7zpnvxqvdjrnr
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *helios
        pgp:
          - *santosh
